language: node_js
sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y uuid-dev
script:
  - npm test
  - npm run lint
  - npm run cover
after_success:
  - npm run report
