dist: trusty
language: node_js
sudo: false
addons:
  apt:
    packages:
      - build-essential
      - uuid-dev
script:
  - npm test
  - npm run lint
  - npm run cover
after_success:
  - npm run report
