name: Turnstile
description: HTTP access control proxy

project:
  owner: rapid7
  repo: turnstile

url: https://rapid7.github.io/turnstile
baseurl: /turnstile

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

collections:
  pages:
    output: true

gems:
  - jemoji
