name: Turnstile
description: HTTP access control proxy

project:
  owner: rapid7
  repo: turnstile

url: https://rapid7.github.io/turnstile
baseurl: /turnstile

markdown: kramdown

collections:
  pages:
    output: true
